import importlib

def integrate_from_model(model_name, func, a, b, params=()):
    """
    Integrates a function using a model generated by generate_integration_py.
    """

    model = importlib.import_module(model_name)
    return model.integrate(func, a, b, params)
